<?php
/**
 * Created by PhpStorm.
 * User: Lw
 * Date: 2018/4/1
 * Time: 18:25
 */

namespace app\controllers;

use Yii;
use yii\web\Controller;

class LoginCheckController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        if(Yii::$app->user->isGuest){
            if (strtoupper($_SERVER['REQUEST_METHOD']) === 'GET' && Yii::$app->request->url == "/index.php?r=site/login" ) {
            } else {
                return $this->redirect('index.php?r=site/login');
            }
        }
    }
}